steps:
  - name: 'hashicorp/terraform:1.5'
    args: ['init']
  - name: 'hashicorp/terraform:1.5'
    args: ['plan']
  - name: 'hashicorp/terraform:1.5'
    args: ['apply', '-auto-approve']
options:
 logging : CLOUD_LOGGING_ONLY
