name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format, Init, Validate, Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # or latest you prefer

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

     # - name: Authenticate to GCP
     #   run: echo "${{ secrets.GCP_CREDENTIALS }}" > account.json
     # - name: Set GOOGLE_APPLICATION_CREDENTIALS
     # run: echo "GOOGLE_APPLICATION_CREDENTIALS=account.json" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
